//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWCF.WCFServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatisticService", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Service")]
    [System.SerializableAttribute()]
    public partial class StatisticService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SuccessTasksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllTasks {
            get {
                return this.AllTasksField;
            }
            set {
                if ((this.AllTasksField.Equals(value) != true)) {
                    this.AllTasksField = value;
                    this.RaisePropertyChanged("AllTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorTasks {
            get {
                return this.ErrorTasksField;
            }
            set {
                if ((this.ErrorTasksField.Equals(value) != true)) {
                    this.ErrorTasksField = value;
                    this.RaisePropertyChanged("ErrorTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuccessTasks {
            get {
                return this.SuccessTasksField;
            }
            set {
                if ((this.SuccessTasksField.Equals(value) != true)) {
                    this.SuccessTasksField = value;
                    this.RaisePropertyChanged("SuccessTasks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="WCFServiceReference.IWcf_Servise", CallbackContract=typeof(ClientWCF.WCFServiceReference.IWcf_ServiseCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWcf_Servise {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWcf_Servise/RunScript", ReplyAction="http://Microsoft.ServiceModel.Samples/IWcf_Servise/RunScriptResponse")]
        void RunScript();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWcf_Servise/RunScript", ReplyAction="http://Microsoft.ServiceModel.Samples/IWcf_Servise/RunScriptResponse")]
        System.Threading.Tasks.Task RunScriptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWcf_Servise/UpdateAndCompile", ReplyAction="http://Microsoft.ServiceModel.Samples/IWcf_Servise/UpdateAndCompileResponse")]
        void UpdateAndCompile(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWcf_Servise/UpdateAndCompile", ReplyAction="http://Microsoft.ServiceModel.Samples/IWcf_Servise/UpdateAndCompileResponse")]
        System.Threading.Tasks.Task UpdateAndCompileAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcf_ServiseCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWcf_Servise/UpdateStatistics", ReplyAction="http://Microsoft.ServiceModel.Samples/IWcf_Servise/UpdateStatisticsResponse")]
        void UpdateStatistics(ClientWCF.WCFServiceReference.StatisticService stats);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcf_ServiseChannel : ClientWCF.WCFServiceReference.IWcf_Servise, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Wcf_ServiseClient : System.ServiceModel.DuplexClientBase<ClientWCF.WCFServiceReference.IWcf_Servise>, ClientWCF.WCFServiceReference.IWcf_Servise {
        
        public Wcf_ServiseClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Wcf_ServiseClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Wcf_ServiseClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Wcf_ServiseClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Wcf_ServiseClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RunScript() {
            base.Channel.RunScript();
        }
        
        public System.Threading.Tasks.Task RunScriptAsync() {
            return base.Channel.RunScriptAsync();
        }
        
        public void UpdateAndCompile(string path) {
            base.Channel.UpdateAndCompile(path);
        }
        
        public System.Threading.Tasks.Task UpdateAndCompileAsync(string path) {
            return base.Channel.UpdateAndCompileAsync(path);
        }
    }
}
